FROM continuumio/miniconda:latest

WORKDIR /home/PyTorch-Docker-Project/

COPY env.yml ./
COPY imagenet_class_index.json ./
COPY __init__.py ./
COPY run.py ./
COPY server.py ./
COPY boot.sh ./

RUN chmod +x boot.sh

RUN Conda env create -f environment.yml

RUN echo "source activate docker del" &gt; ~/.bashrc
ENV PATH /opt/conda/envs/docker_del/bin:$PATH

EXPOSE 5000

ENTRYPOINT ["./boot.sh"]